var loadVoskletto=(()=>{var _scriptName=typeof document!="undefined"?document.currentScript?.src:undefined;return async function(moduleArg={}){var moduleRtn;var l=moduleArg,p="em-ww"==globalThis.name,aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca=(a,b)=>void 0===a||a.split("?")[1]!==b,da=()=>{registerProcessor("voskletto-transferer",class extends AudioWorkletProcessor{constructor(a){super();this.ia=0;this.xa=a.processorOptions[0];this.ua=new Float32Array(this.xa)}process(a){a[0][0]&&(this.ua.set(a[0][0],this.ia),this.ia+=128,this.ia>=this.xa&&(this.ia=0,this.port.postMessage(this.ua,[this.ua.buffer]),this.ua=new Float32Array(this.xa)));
return!0}})},ea=async(a,b,c)=>{await a.audioWorklet.addModule(b);return new AudioWorkletNode(a,"voskletto-transferer",{channelCountMode:"explicit",numberOfInputs:1,numberOfOutputs:0,channelCount:1,processorOptions:[c]})};
if(!p){q=[];const a=l.cacheName??"voskletto",b=caches.open(a),c=URL.createObjectURL(new Blob(["(",da.toString(),")()"],{type:"text/javascript"})),d=e=>new Promise((g,k)=>{e.addEventListener("",n=>{(n=n.detail)?k(n):g(e)},{once:!0})});class f extends EventTarget{constructor(){super();q.push(this)}delete(){this.da.delete()}static async ia(e,g,k,n){const m=new f,w=d(m).then(u=>{n&&(u.findWord=z=>u.da.findWord(z));return u}),v=await caches.open(a),r=(await v.keys(g,{ignoreSearch:!0}))[0];if(ca(r?.url,
k)){e=await fetch(e,{cache:"no-store"});if(!e.ok)throw"Unable to fetch model, status: "+e.status;e=new Response(e.body.pipeThrough(new DecompressionStream("gzip")));await v.put(g+"?"+k,e.clone())}else e=await v.match(r);g=await e.arrayBuffer();k=t(g.byteLength);(x(),y).set(new Uint8Array(g),k);m.da=new l.CommonModel(q.indexOf(m),n,k,g.byteLength);return w}}class h extends EventTarget{constructor(){super();q.push(this);this.acceptWaveform=e=>{const g=t(4*e.length);(x(),fa).set(e,g/4);try{var k={ok:!0,
json:this.da.acceptWaveform(g,e.length)}}catch(n){k={ok:!1,error:n}}finally{A(g)}a:{e=k;if(!e.ok||""===e.json){e.ok?k=Error("Unable to recognize audio"):(k=e.error,k=k instanceof Error?k:Error(String(k)));if(!this.dispatchEvent(new CustomEvent("error",{detail:k,cancelable:!0}))||e.ok){e="";break a}throw e.error;}k=e.json;k.startsWith("<")?k={type:"nlsml",detail:k}:(k=JSON.parse(k),k="partial"in k?{type:"partialResult",detail:k}:"alternatives"in k?{type:"alternatives",detail:k.alternatives}:{type:"result",
detail:k});const {type:n,detail:m}=k;this.dispatchEvent(new CustomEvent(n,{detail:m}));e=e.json}return e};this.setWords=e=>this.da.setWords(e);this.setPartialWords=e=>this.da.setPartialWords(e);this.setNLSML=e=>this.da.setNLSML(e);this.setMaxAlternatives=e=>this.da.setMaxAlternatives(e);this.setGrm=e=>this.da.setGrm(e);this.setSpkModel=e=>this.da.setSpkModel(e.da);this.setEndpointerMode=e=>this.da.setEndpointerMode(e);this.setEndpointerDelays=(e,g,k)=>this.da.setEndpointerDelays(e,g,k);this.reset=
()=>this.da.reset()}delete(){this.da.delete()}static async ia(e,g,k,n,m){const w=new h,v=d(w),r=l.Recognizer;switch(k){case 1:w.da=new r(q.length-1,g,e);break;case 2:w.da=new r(q.length-1,g,e,m);break;default:w.da=new r(q.length-1,g,e,n,0)}return v}}l={getModelCache:()=>b,cleanUp:async()=>{for(const e of q)await e.delete();URL.revokeObjectURL(c)},createTransferer:(e,g)=>ea(e,c,g),createModel:(e,g,k)=>f.ia(e,g,k,!0),createSpkModel:(e,g,k)=>f.ia(e,g,k,!1),createRecognizer:(e,g)=>h.ia(e.da,g,1),createRecognizerWithGrm:(e,
g,k)=>h.ia(e.da,g,3,k,null),createRecognizerWithSpkModel:(e,g,k)=>h.ia(e.da,g,2,null,k.da)}}var q;ba&&(_scriptName=self.location.href);var ha="",ia,ja;if(aa||ba){try{ha=(new URL(".",_scriptName)).href}catch{}ba&&(ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});ia=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);}}
var ka=console.log.bind(console),B=console.error.bind(console),la=!1;function x(){D.buffer!=E.buffer&&ma()}var na,oa,pa,qa;p&&(onmessage=a=>{onmessage=null;qa=a=a.data;D=a.Wa;ma();pa(a.Oa);a.Oa=a.Qa=0});var D,E,y,F,G,H,I,fa,ra,sa,ta,ua=!1;function ma(){var a=D.buffer;E=new Int8Array(a);F=new Int16Array(a);y=new Uint8Array(a);G=new Uint16Array(a);H=new Int32Array(a);I=new Uint32Array(a);fa=new Float32Array(a);ra=new Float64Array(a);sa=new BigInt64Array(a);ta=new BigUint64Array(a)}
function va(){ua=!0;p?(wa(qa.Ta,qa.Ua),xa(),removeEventListener("message",ya),za=za.forEach(Ca),addEventListener("message",Ca)):J.T()}var K=0,L=null;function Da(a){a="Aborted("+a+")";B(a);la=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");oa?.(a);throw a;}var Ea;async function Fa(a){try{var b=await ia(a);return new Uint8Array(b)}catch{}if(ja)a=ja(a);else throw"both async and sync fetching of the wasm failed";return a}
async function Ga(a,b){try{var c=await Fa(a);return await WebAssembly.instantiate(c,b)}catch(d){B(`failed to asynchronously prepare wasm: ${d}`),Da(d)}}async function Ha(a){var b=Ea;try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){B(`wasm streaming compile failed: ${d}`),B("falling back to ArrayBuffer instantiation")}return Ga(b,a)}
function Ia(){Ja={b:Ka,c:La,J:Ma,q:Na,N:Oa,o:Pa,i:Qa,f:Ra,L:Sa,K:Ta,j:Ua,p:Va,S:Wa,g:Xa,d:Ya,M:Za,m:$a,O:ab,s:bb,t:cb,F:db,A:eb,y:fb,z:gb,w:hb,u:ib,B:jb,x:kb,v:lb,D:nb,P:ob,R:pb,Q:qb,e:rb,k:sb,l:tb,C:ub,G:vb,H:wb,I:xb,n:yb,h:zb,a:D,r:Ab,E:Bb};return{a:Ja}}class Cb{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var za=[],Ab=a=>{throw new Cb(a);},yb=a=>{throw new Cb(a);},Db=a=>{if(!la)try{a()}catch(b){if(!(b instanceof Cb||"unwind"==b))throw b;}},Eb=[],Fb,Gb=a=>{var b=Eb[a];b||(Eb[a]=b=Fb.get(a));return b},Ca=a=>{let b=a.data,c=b._wsc;c&&Db(()=>Gb(c)(...b.x))},ya=a=>{za.push(a)},Hb=new TextDecoder,Ib=(a,b,c,d)=>{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},M=(a,b,c)=>{if(!a)return"";b=Ib((x(),y),a,b,c);return Hb.decode((x(),y).slice(a,b))},Ka=(a,b,c,d)=>Da(`Assertion failed: ${M(a)}, at: `+[b?M(b):
"unknown filename",c,d?M(d):"unknown function"]);class Jb{constructor(a){this.ba=a-24}}var Kb=0,Lb=0,La=(a,b,c)=>{var d=new Jb(a);(x(),I)[d.ba+16>>2]=0;(x(),I)[d.ba+4>>2]=b;(x(),I)[d.ba+8>>2]=c;Kb=a;Lb++;throw Kb;},Ma=()=>Da(""),N=a=>{for(var b="";;){var c=(x(),y)[a++];if(!c)return b;b+=String.fromCharCode(c)}},O={},P={},Mb={},Q=class extends Error{constructor(a){super(a);this.name="BindingError"}},Nb=a=>{throw new Q(a);};
function Ob(a,b,c={}){var d=b.name;if(!a)throw new Q(`type "${d}" must have a positive integer typeid pointer`);if(P.hasOwnProperty(a)){if(c.Ha)return;throw new Q(`Cannot register type '${d}' twice`);}P[a]=b;delete Mb[a];O.hasOwnProperty(a)&&(b=O[a],delete O[a],b.forEach(f=>f()))}function R(a,b,c={}){return Ob(a,b,c)}
var Pb=(a,b,c)=>{switch(b){case 1:return c?d=>(x(),E)[d]:d=>(x(),y)[d];case 2:return c?d=>(x(),F)[d>>1]:d=>(x(),G)[d>>1];case 4:return c?d=>(x(),H)[d>>2]:d=>(x(),I)[d>>2];case 8:return c?d=>(x(),sa)[d>>3]:d=>(x(),ta)[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Na=(a,b,c,d,f)=>{b=N(b);d=0n===d;let h=e=>e;if(d){const e=8*c;h=g=>BigInt.asUintN(e,g);f=h(f)}R(a,{name:b,ca:h,la:(e,g)=>{"number"==typeof g&&(g=BigInt(g));return g},ma:Pb(b,c,!d),ja:null})},Oa=(a,b,c,d)=>{b=N(b);
R(a,{name:b,ca:function(f){return!!f},la:function(f,h){return h?c:d},ma:function(f){return this.ca((x(),y)[f])},ja:null})},Qb=a=>{throw new Q(a.$.ea.aa.name+" instance already deleted");},Rb=!1,Sb=()=>{},S=a=>{if("undefined"===typeof FinalizationRegistry)return S=b=>b,a;Rb=new FinalizationRegistry(b=>{b=b.$;--b.count.value;0===b.count.value&&(b.ga?b.ka.na(b.ga):b.ea.aa.na(b.ba))});S=b=>{var c=b.$;c.ga&&Rb.register(b,{$:c},b);return b};Sb=b=>{Rb.unregister(b)};return S(a)},Tb=[];function Ub(){}
var Vb=(a,b)=>Object.defineProperty(b,"name",{value:a}),Wb={},Xb=(a,b,c)=>{if(void 0===a[b].fa){var d=a[b];a[b]=function(...f){if(!a[b].fa.hasOwnProperty(f.length))throw new Q(`Function '${c}' called with an invalid number of arguments (${f.length}) - expects one of (${a[b].fa})!`);return a[b].fa[f.length].apply(this,f)};a[b].fa=[];a[b].fa[d.qa]=d}},Yb=(a,b,c)=>{if(l.hasOwnProperty(a)){if(void 0===c||void 0!==l[a].fa&&void 0!==l[a].fa[c])throw new Q(`Cannot register public name '${a}' twice`);Xb(l,
a,a);if(l[a].fa.hasOwnProperty(c))throw new Q(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);l[a].fa[c]=b}else l[a]=b,l[a].qa=c},Zb=a=>{a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a};function $b(a,b,c,d,f,h,e,g){this.name=a;this.constructor=b;this.pa=c;this.na=d;this.ha=f;this.Fa=h;this.ta=e;this.Da=g;this.Ka=[]}
var ac=(a,b,c)=>{for(;b!==c;){if(!b.ta)throw new Q(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.ta(a);b=b.ha}return a},bc=a=>{if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a};
function cc(a,b){if(null===b){if(this.ya)throw new Q(`null is not a valid ${this.name}`);return 0}if(!b.$)throw new Q(`Cannot pass "${bc(b)}" as a ${this.name}`);if(!b.$.ba)throw new Q(`Cannot pass deleted object as a pointer of type ${this.name}`);return ac(b.$.ba,b.$.ea.aa,this.aa)}
function dc(a,b){if(null===b){if(this.ya)throw new Q(`null is not a valid ${this.name}`);if(this.wa){var c=this.La();null!==a&&a.push(this.na,c);return c}return 0}if(!b||!b.$)throw new Q(`Cannot pass "${bc(b)}" as a ${this.name}`);if(!b.$.ba)throw new Q(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.va&&b.$.ea.va)throw new Q(`Cannot convert argument of type ${b.$.ka?b.$.ka.name:b.$.ea.name} to parameter type ${this.name}`);c=ac(b.$.ba,b.$.ea.aa,this.aa);if(this.wa){if(void 0===
b.$.ga)throw new Q("Passing raw pointer to smart pointer is illegal");switch(this.Na){case 0:if(b.$.ka===this)c=b.$.ga;else throw new Q(`Cannot convert argument of type ${b.$.ka?b.$.ka.name:b.$.ea.name} to parameter type ${this.name}`);break;case 1:c=b.$.ga;break;case 2:if(b.$.ka===this)c=b.$.ga;else{var d=b.clone();c=this.Ma(c,ec(()=>d["delete"]()));null!==a&&a.push(this.na,c)}break;default:throw new Q("Unsupporting sharing policy");}}return c}
function fc(a,b){if(null===b){if(this.ya)throw new Q(`null is not a valid ${this.name}`);return 0}if(!b.$)throw new Q(`Cannot pass "${bc(b)}" as a ${this.name}`);if(!b.$.ba)throw new Q(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.$.ea.va)throw new Q(`Cannot convert argument of type ${b.$.ea.name} to parameter type ${this.name}`);return ac(b.$.ba,b.$.ea.aa,this.aa)}function gc(a){return this.ca((x(),I)[a>>2])}
var hc=(a,b,c)=>{if(b===c)return a;if(void 0===c.ha)return null;a=hc(a,b,c.ha);return null===a?null:c.Da(a)},ic={},jc=(a,b)=>{if(void 0===b)throw new Q("ptr should not be undefined");for(;a.ha;)b=a.ta(b),a=a.ha;return ic[b]},kc=class extends Error{constructor(a){super(a);this.name="InternalError"}},lc=(a,b)=>{if(!b.ea||!b.ba)throw new kc("makeClassHandle requires ptr and ptrType");if(!!b.ka!==!!b.ga)throw new kc("Both smartPtrType and smartPtr must be specified");b.count={value:1};return S(Object.create(a,
{$:{value:b,writable:!0}}))};function mc(a,b,c,d,f,h,e,g,k,n,m){this.name=a;this.aa=b;this.ya=c;this.va=d;this.wa=f;this.Ja=h;this.Na=e;this.Ba=g;this.La=k;this.Ma=n;this.na=m;f||void 0!==b.ha?this.la=dc:(this.la=d?cc:fc,this.ja=null)}
var nc=(a,b,c)=>{if(!l.hasOwnProperty(a))throw new kc("Replacing nonexistent public symbol");void 0!==l[a].fa&&void 0!==c?l[a].fa[c]=b:(l[a]=b,l[a].qa=c)},T=(a,b)=>{a=N(a);var c=Gb(b);if("function"!=typeof c)throw new Q(`unknown function pointer with signature ${a}: ${b}`);return c};class oc extends Error{}
var qc=a=>{a=pc(a);var b=N(a);A(a);return b},rc=(a,b)=>{function c(h){f[h]||P[h]||(Mb[h]?Mb[h].forEach(c):(d.push(h),f[h]=!0))}var d=[],f={};b.forEach(c);throw new oc(`${a}: `+d.map(qc).join([", "]));},U=(a,b,c)=>{function d(g){g=c(g);if(g.length!==a.length)throw new kc("Mismatched type converter count");for(var k=0;k<a.length;++k)R(a[k],g[k])}a.forEach(g=>Mb[g]=b);var f=Array(b.length),h=[],e=0;b.forEach((g,k)=>{P.hasOwnProperty(g)?f[k]=P[g]:(h.push(g),O.hasOwnProperty(g)||(O[g]=[]),O[g].push(()=>
{f[k]=P[g];++e;e===h.length&&d(f)}))});0===h.length&&d(f)},Pa=(a,b,c,d,f,h,e,g,k,n,m,w,v)=>{m=N(m);h=T(f,h);g&&=T(e,g);n&&=T(k,n);v=T(w,v);var r=Zb(m);Yb(r,function(){rc(`Cannot construct ${m} due to unbound types`,[d])});U([a,b,c],d?[d]:[],u=>{u=u[0];if(d){var z=u.aa;var Y=z.pa}else Y=Ub.prototype;u=Vb(m,function(...Aa){if(Object.getPrototypeOf(this)!==Ba)throw new Q(`Use 'new' to construct ${m}`);if(void 0===C.oa)throw new Q(`${m} has no accessible constructor`);var mb=C.oa[Aa.length];if(void 0===
mb)throw new Q(`Tried to invoke ctor of ${m} with invalid number of parameters (${Aa.length}) - expected (${Object.keys(C.oa).toString()}) parameters instead!`);return mb.apply(this,Aa)});var Ba=Object.create(Y,{constructor:{value:u}});u.prototype=Ba;var C=new $b(m,u,Ba,v,z,h,g,n);if(C.ha){var Z;(Z=C.ha).za??(Z.za=[]);C.ha.za.push(C)}z=new mc(m,C,!0,!1,!1);Z=new mc(m+"*",C,!1,!1,!1);Y=new mc(m+" const*",C,!1,!0,!1);Wb[a]={pointerType:Z,Ca:Y};nc(r,u);return[z,Z,Y]})},sc=(a,b)=>{for(var c=[],d=0;d<
a;d++)c.push((x(),I)[b+4*d>>2]);return c},tc=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function uc(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].ja)return!0;return!1}
function vc(a,b,c,d,f,h){var e=b.length;if(2>e)throw new Q("argTypes array size mismatch! Must at least get return value and 'this' types!");var g=null!==b[1]&&null!==c,k=uc(b);c=!b[0].Ia;var n=b[0],m=b[1];d=[a,Nb,d,f,tc,n.ca.bind(n),m?.la.bind(m)];for(f=2;f<e;++f)n=b[f],d.push(n.la.bind(n));if(!k)for(f=g?1:2;f<b.length;++f)null!==b[f].ja&&d.push(b[f].ja);k=uc(b);f=b.length-2;m=[];n=["fn"];g&&n.push("thisWired");for(e=0;e<f;++e)m.push(`arg${e}`),n.push(`arg${e}Wired`);m=m.join(",");n=n.join(",");
m=`return function (${m}) {\n`;k&&(m+="var destructors = [];\n");var w=k?"destructors":"null",v="humanName throwBindingError invoker fn runDestructors fromRetWire toClassParamWire".split(" ");g&&(m+=`var thisWired = toClassParamWire(${w}, this);\n`);for(e=0;e<f;++e){var r=`toArg${e}Wire`;m+=`var arg${e}Wired = ${r}(${w}, arg${e});\n`;v.push(r)}m+=(c||h?"var rv = ":"")+`invoker(${n});\n`;if(k)m+="runDestructors(destructors);\n";else for(e=g?1:2;e<b.length;++e)h=1===e?"thisWired":"arg"+(e-2)+"Wired",
null!==b[e].ja&&(m+=`${h}_dtor(${h});\n`,v.push(`${h}_dtor`));c&&(m+="var ret = fromRetWire(rv);\nreturn ret;\n");b=(new Function(v,m+"}\n"))(...d);return Vb(a,b)}
var Qa=(a,b,c,d,f,h)=>{var e=sc(b,c);f=T(d,f);U([],[a],g=>{g=g[0];var k=`constructor ${g.name}`;void 0===g.aa.oa&&(g.aa.oa=[]);if(void 0!==g.aa.oa[b-1])throw new Q(`Cannot register multiple constructors with identical number of parameters (${b-1}) for class '${g.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);g.aa.oa[b-1]=()=>{rc(`Cannot construct ${g.name} due to unbound types`,e)};U([],e,n=>{n.splice(1,0,null);g.aa.oa[b-1]=vc(k,n,null,f,
h);return[]});return[]})},wc=a=>{a=a.trim();const b=a.indexOf("(");return-1===b?a:a.slice(0,b)},Ra=(a,b,c,d,f,h,e,g,k)=>{var n=sc(c,d);b=N(b);b=wc(b);h=T(f,h);U([],[a],m=>{function w(){rc(`Cannot call ${v} due to unbound types`,n)}m=m[0];var v=`${m.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);g&&m.aa.Ka.push(b);var r=m.aa.pa,u=r[b];void 0===u||void 0===u.fa&&u.className!==m.name&&u.qa===c-2?(w.qa=c-2,w.className=m.name,r[b]=w):(Xb(r,b,v),r[b].fa[c-2]=w);U([],n,z=>{z=vc(v,z,m,h,e,k);
void 0===r[b].fa?(z.qa=c-2,r[b]=z):r[b].fa[c-2]=z;return[]});return[]})},xc=[],V=[0,1,,1,null,1,!0,1,!1,1],ec=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=xc.pop()||V.length;V[b]=a;V[b+1]=1;return b}},yc={name:"emscripten::val",ca:a=>{if(!a)throw new Q(`Cannot use deleted val. handle = ${a}`);var b=V[a];9<a&&0===--V[a+1]&&(V[a]=void 0,xc.push(a));return b},la:(a,b)=>ec(b),ma:gc,ja:null},Sa=a=>R(a,yc),zc=(a,b,c)=>{switch(b){case 1:return c?
function(d){return this.ca((x(),E)[d])}:function(d){return this.ca((x(),y)[d])};case 2:return c?function(d){return this.ca((x(),F)[d>>1])}:function(d){return this.ca((x(),G)[d>>1])};case 4:return c?function(d){return this.ca((x(),H)[d>>2])}:function(d){return this.ca((x(),I)[d>>2])};default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Ta=(a,b,c,d)=>{function f(){}b=N(b);f.values={};R(a,{name:b,constructor:f,ca:function(h){return this.constructor.values[h]},la:(h,e)=>e.value,ma:zc(b,
c,d),ja:null});Yb(b,f)},Ac=a=>{var b=P[a];if(void 0===b)throw a=`${"enum"} has unknown type ${qc(a)}`,new Q(a);return b},Ua=(a,b,c)=>{var d=Ac(a);b=N(b);a=d.constructor;d=Object.create(d.constructor.prototype,{value:{value:c},constructor:{value:Vb(`${d.name}_${b}`,function(){})}});a.values[c]=d;a[b]=d},Bc=(a,b)=>{switch(b){case 4:return function(c){return this.ca((x(),fa)[c>>2])};case 8:return function(c){return this.ca((x(),ra)[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);
}},Va=(a,b,c)=>{b=N(b);R(a,{name:b,ca:d=>d,la:(d,f)=>f,ma:Bc(b,c),ja:null})},Wa=(a,b,c,d,f,h,e)=>{var g=sc(b,c);a=N(a);a=wc(a);f=T(d,f);Yb(a,function(){rc(`Cannot call ${a} due to unbound types`,g)},b-1);U([],g,k=>{nc(a,vc(a,[k[0],null].concat(k.slice(1)),null,f,h,e),b-1);return[]})},Xa=(a,b,c,d,f)=>{b=N(b);let h=g=>g;if(0===d){var e=32-8*c;h=g=>g<<e>>>e;f=h(f)}R(a,{name:b,ca:h,la:(g,k)=>k,ma:Pb(b,c,0!==d),ja:null})},Ya=(a,b,c)=>{function d(h){var e=(x(),I)[h>>2];h=(x(),I)[h+4>>2];return new f((x(),
E).buffer,h,e)}var f=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=N(c);R(a,{name:c,ca:d,ma:d},{Ha:!0})},Cc=(a,b,c,d)=>{if(!(0<d))return 0;var f=c;d=c+d-1;for(var h=0;h<a.length;++h){var e=a.codePointAt(h);if(127>=e){if(c>=d)break;b[c++]=e}else if(2047>=e){if(c+1>=d)break;b[c++]=192|e>>6;b[c++]=128|e&63}else if(65535>=e){if(c+2>=d)break;b[c++]=224|e>>12;b[c++]=128|e>>6&63;b[c++]=128|e&63}else{if(c+3>=d)break;b[c++]=
240|e>>18;b[c++]=128|e>>12&63;b[c++]=128|e>>6&63;b[c++]=128|e&63;h++}}b[c]=0;return c-f},W=(a,b,c)=>Cc(a,(x(),y),b,c),X=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Za=(a,b)=>{b=N(b);R(a,{name:b,ca(c){var d=(x(),I)[c>>2];d=M(c+4,d,!0);A(c);return d},la(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var f="string"==typeof d;if(!(f||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new Q("Cannot pass non-string to std::string");
var h=f?X(d):d.length;var e=t(4+h+1),g=e+4;(x(),I)[e>>2]=h;f?W(d,g,h+1):(x(),y).set(d,g);null!==c&&c.push(A,e);return e},ma:gc,ja(c){A(c)}})},Dc=new TextDecoder("utf-16le"),Ec=(a,b,c)=>{a>>=1;b=Ib((x(),G),a,b/2,c);return Dc.decode((x(),G).buffer instanceof ArrayBuffer?(x(),G).subarray(a,b):(x(),G).slice(a,b))},Fc=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var f=0;f<c;++f){var h=a.charCodeAt(f);(x(),F)[b>>1]=h;b+=2}(x(),F)[b>>1]=0;return b-d},Gc=a=>2*a.length,
Hc=(a,b,c)=>{var d="";a>>=2;for(var f=0;!(f>=b/4);f++){var h=(x(),I)[a+f];if(!h&&!c)break;d+=String.fromCodePoint(h)}return d},Ic=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var f=0;f<a.length;++f){var h=a.codePointAt(f);65535<h&&f++;(x(),H)[b>>2]=h;b+=4;if(b+4>c)break}(x(),H)[b>>2]=0;return b-d},Jc=a=>{for(var b=0,c=0;c<a.length;++c)65535<a.codePointAt(c)&&c++,b+=4;return b},$a=(a,b,c)=>{c=N(c);if(2===b){var d=Ec;var f=Fc;var h=Gc}else d=Hc,f=Ic,h=Jc;R(a,{name:c,ca:e=>{var g=(x(),
I)[e>>2];g=d(e+4,g*b,!0);A(e);return g},la:(e,g)=>{if("string"!=typeof g)throw new Q(`Cannot pass non-string to C++ string type ${c}`);var k=h(g),n=t(4+k+b);(x(),I)[n>>2]=k/b;f(g,n+4,k+b);null!==e&&e.push(A,n);return n},ma:gc,ja(e){A(e)}})},ab=(a,b)=>{b=N(b);R(a,{Ia:!0,name:b,ca:()=>{},la:()=>{}})},bb=()=>{},Kc={},tb=()=>performance.now(),cb=(a,b)=>{Kc[a]&&(clearTimeout(Kc[a].id),delete Kc[a]);if(!b)return 0;var c=setTimeout(()=>{delete Kc[a];Db(()=>Lc(a,performance.now()))},b);Kc[a]={id:c,Va:b};
return 0},db=(a,b,c,d)=>{var f=(new Date).getFullYear(),h=(new Date(f,0,1)).getTimezoneOffset();f=(new Date(f,6,1)).getTimezoneOffset();var e=Math.max(h,f);(x(),I)[a>>2]=60*e;(x(),H)[b>>2]=Number(h!=f);b=g=>{var k=Math.abs(g);return`UTC${0<=g?"-":"+"}${String(Math.floor(k/60)).padStart(2,"0")}${String(k%60).padStart(2,"0")}`};a=b(h);b=b(f);f<h?(W(a,c,17),W(b,d,17)):(W(a,d,17),W(b,c,17))},eb=(a,b)=>(x(),y).set(Mc[a].Ea,b),Nc=[],fb=()=>Nc.length,Mc=[],gb=()=>Mc.length,hb=(a,b)=>{a=Nc[a].Pa;W(a,b,X(a)+
1)},ib=a=>Mc[a].mode,jb=a=>Mc[a].Ea.length,kb=(a,b)=>{a=Nc[a].Ra;W(a,b,X(a)+1)},lb=(a,b)=>{a=Mc[a].Sa;W(a,b,X(a)+1)},Oc=[],nb=()=>{a:{if(!Oc.length){var a=null;"undefined"!=typeof window&&"function"==typeof window.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){var b=null;break a}b=Array(X(a)+1);a=Cc(a,b,0,b.length);b.length=a;Oc=b}b=Oc.shift()}return"number"===typeof b?b:-1},ob=a=>{console.error(M(a))},pb=a=>{console.log(M(a))},qb=a=>{console.warn(M(a))},rb=()=>Date.now(),sb=a=>B(M(a)),
ub=a=>ka(M(a)),vb=a=>{var b=(x(),y).length;a>>>=0;if(a<=b||2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-D.buffer.byteLength+65535)/65536|0;try{D.grow(d);ma();var f=1;break a}catch(h){}f=void 0}if(f)return!0}return!1},Pc={},Rc=()=>{if(!Qc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.language||"C").replace("-","_")+
".UTF-8",_:"./this.program"},b;for(b in Pc)void 0===Pc[b]?delete a[b]:a[b]=Pc[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Qc=c}return Qc},Qc,wb=(a,b)=>{var c=0,d=0,f;for(f of Rc()){var h=b+c;(x(),I)[a+d>>2]=h;c+=W(f,h,Infinity)+1;d+=4}return 0},xb=(a,b)=>{var c=Rc();(x(),I)[a>>2]=c.length;a=0;for(var d of c)a+=X(d)+1;(x(),I)[b>>2]=a;return 0},Sc=()=>a=>a.set(crypto.getRandomValues(new Uint8Array(a.byteLength))),Tc=a=>{(Tc=Sc())(a)},Bb=(a,b)=>{Tc((x(),y).subarray(a,a+b));return 0};
(()=>{let a=Ub.prototype;Object.assign(a,{isAliasOf:function(c){if(!(this instanceof Ub&&c instanceof Ub))return!1;var d=this.$.ea.aa,f=this.$.ba;c.$=c.$;var h=c.$.ea.aa;for(c=c.$.ba;d.ha;)f=d.ta(f),d=d.ha;for(;h.ha;)c=h.ta(c),h=h.ha;return d===h&&f===c},clone:function(){this.$.ba||Qb(this);if(this.$.sa)return this.$.count.value+=1,this;var c=S,d=Object,f=d.create,h=Object.getPrototypeOf(this),e=this.$;c=c(f.call(d,h,{$:{value:{count:e.count,ra:e.ra,sa:e.sa,ba:e.ba,ea:e.ea,ga:e.ga,ka:e.ka}}}));c.$.count.value+=
1;c.$.ra=!1;return c},["delete"](){this.$.ba||Qb(this);if(this.$.ra&&!this.$.sa)throw new Q("Object already scheduled for deletion");Sb(this);var c=this.$;--c.count.value;0===c.count.value&&(c.ga?c.ka.na(c.ga):c.ea.aa.na(c.ba));this.$.sa||(this.$.ga=void 0,this.$.ba=void 0)},isDeleted:function(){return!this.$.ba},deleteLater:function(){this.$.ba||Qb(this);if(this.$.ra&&!this.$.sa)throw new Q("Object already scheduled for deletion");Tb.push(this);this.$.ra=!0;return this}});const b=Symbol.dispose;
b&&(a[b]=a["delete"])})();
Object.assign(mc.prototype,{Ga(a){this.Ba&&(a=this.Ba(a));return a},Aa(a){this.na?.(a)},ma:gc,ca:function(a){function b(){return this.wa?lc(this.aa.pa,{ea:this.Ja,ba:c,ka:this,ga:a}):lc(this.aa.pa,{ea:this,ba:a})}var c=this.Ga(a);if(!c)return this.Aa(a),null;var d=jc(this.aa,c);if(void 0!==d){if(0===d.$.count.value)return d.$.ba=c,d.$.ga=a,d.clone();d=d.clone();this.Aa(a);return d}d=this.aa.Fa(c);d=Wb[d];if(!d)return b.call(this);d=this.va?d.Ca:d.pointerType;var f=hc(c,this.aa,d.aa);return null===
f?b.call(this):this.wa?lc(d.aa.pa,{ea:d,ba:f,ka:this,ga:a}):lc(d.aa.pa,{ea:d,ba:f})}});p||(l.wasmMemory?D=l.wasmMemory:D=new WebAssembly.Memory({initial:5040,maximum:32768,shared:!0}),ma());function zb(a,b){q[a].dispatchEvent(new CustomEvent("",{detail:0==b?null:M(b)}))}
var A,t,pc,xa,Lc,wa,Ja,J=await (async function(){function a(c){J=c.exports;Fb=J.Y;c=J;A=c.U;t=c.V;pc=c.W;xa=c.X;Lc=c.Z;wa=c._;K--;0==K&&L&&(c=L,L=null,c());return J}K++;var b=Ia();if(l.instantiateWasm)return new Promise(c=>{l.instantiateWasm(b,(d,f)=>{c(a(d,f))})});if(p)return new Promise(c=>{pa=d=>{var f=new WebAssembly.Instance(d,Ia());c(a(f,d))}});Ea??=ha+"voskletto.wasm";return function(c){return a(c.instance,c.module)}(await Ha(b))}());
function Uc(){0<K?L=Uc:p?(na?.(l),va()):0<K?L=Uc:(l.calledRun=!0,la||(va(),na?.(l)))}Uc();ua?moduleRtn=l:moduleRtn=new Promise((a,b)=>{na=a;oa=b});
;return moduleRtn}})();if(typeof exports==="object"&&typeof module==="object"){module.exports=loadVoskletto;module.exports.default=loadVoskletto}else if(typeof define==="function"&&define["amd"])define([],()=>loadVoskletto);var isWW=globalThis.self?.name=="em-ww";isWW&&loadVoskletto();
